using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlowGenerator
{
    [Generator]
    public sealed class GraphFlowGenerator : ISourceGenerator
    {
        const string GraphNodeDefinitionBase = "Scaffold.GraphFlow.GraphNodeDefinitionBase";
        const string GraphNodeDefinitionBaseGeneric = "Scaffold.GraphFlow.GraphNodeDefinitionBase`1";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver is not Receiver rx)
                return;

            var list = new List<INamedTypeSymbol>();
            foreach (var typeDecl in rx.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(typeDecl.SyntaxTree);
                var sym = model.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
                if (sym == null || IsGeneratedPartial(sym))
                    continue;
                if (!InheritsGraphDefinition(sym))
                    continue;
                list.Add(sym);
            }

            if (list.Count == 0)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Scaffold.GraphFlow;");
            sb.AppendLine();
            foreach (var sym in list.OrderBy(s => s.ToDisplayString()))
            {
                var fq = sym.ToDisplayString();
                var literal = ToStringLiteral(fq);
                var name = sym.Name;
                sb.AppendLine($"namespace {sym.ContainingNamespace.ToDisplayString()}");
                sb.AppendLine("{");
                sb.AppendLine($"    partial class {name}");
                sb.AppendLine("    {");
                sb.AppendLine($"        public override string DefinitionTypeId => {literal};");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }

            sb.AppendLine("namespace Scaffold.GraphFlow.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GraphFlowGeneratedRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void RegisterAll(GraphFlowRegistry registry)");
            sb.AppendLine("        {");
            foreach (var sym in list.OrderBy(s => s.ToDisplayString()))
            {
                var fq = sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            registry.Register(new {fq}());");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            context.AddSource("GraphFlowDefinitions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static string ToStringLiteral(string s) =>
            "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

        static bool IsGeneratedPartial(INamedTypeSymbol sym) =>
            sym.Name.Contains("Generated") || (sym.ContainingType?.Name == "GraphFlowGeneratedRegistration");

        static bool InheritsGraphDefinition(INamedTypeSymbol sym)
        {
            for (var b = sym.BaseType; b != null; b = b.BaseType)
            {
                var n = b.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (n == GraphNodeDefinitionBase)
                    return true;
                if (b.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == GraphNodeDefinitionBaseGeneric)
                    return true;
            }

            return false;
        }

        sealed class Receiver : ISyntaxContextReceiver
        {
            internal readonly List<ClassDeclarationSyntax> Candidates = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
            {
                if (context.Node is ClassDeclarationSyntax cds && cds.Modifiers.Any(SyntaxKind.PartialKeyword))
                    Candidates.Add(cds);
            }
        }
    }
}
