using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.LiveOps.Bootstrap.Generators
{
    [Generator]
    public sealed class LiveOpsManifestGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                (sp, compilation) => Execute(sp, compilation));
        }

        private static void Execute(SourceProductionContext context, Compilation compilation)
        {
            INamedTypeSymbol? iGameHandler2 = compilation.GetTypeByMetadataName("LiveOps.GameApi.IGameApiHandler`2");
            INamedTypeSymbol? iModule = compilation.GetTypeByMetadataName("LiveOps.GameModule.IGameModule");
            var types = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            VisitAssembly(compilation.Assembly, types);
            foreach (MetadataReference reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol refSym)
                {
                    continue;
                }

                if (IsRelevantRef(refSym))
                {
                    VisitAssembly(refSym, types);
                }
            }

            EmitLiveOpsKeysCatalog(context, compilation, types);
            ReportWireKeyCollisionsIfAny(context, compilation, types);
            if (iGameHandler2 is null && iModule is null)
            {
                EmitEmpty(context);
                return;
            }

            var list = new List<Entry>(types.Count);
            foreach (INamedTypeSymbol t in types)
            {
                if (t.IsAbstract)
                {
                    continue;
                }

                if (t.TypeKind is not (TypeKind.Class or TypeKind.Struct))
                {
                    continue;
                }

                ITypeSymbol? req = null;
                ITypeSymbol? res = null;
                bool h = iGameHandler2 is not null && TryGetHandlerArgs(t, iGameHandler2, out req, out res);
                bool m = iModule is not null && ImplementsInterface(t, iModule);
                if (h || m)
                {
                    list.Add(new Entry(t, h, m, h ? req : null, h ? res : null));
                }
            }

            Emit(context, list);
        }

        private static void EmitLiveOpsKeysCatalog(
            SourceProductionContext context,
            Compilation compilation,
            IReadOnlyCollection<INamedTypeSymbol> types)
        {
            INamedTypeSymbol? keyAttr = compilation.GetTypeByMetadataName("LiveOps.DTO.Keys.LiveOpsKeyAttribute");
            if (keyAttr is null)
            {
                return;
            }

            var valueToIdentifier = new Dictionary<string, string>(StringComparer.Ordinal);
            var usedConstNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (INamedTypeSymbol t in types)
            {
                if (t is null)
                {
                    continue;
                }

                if (t.GetAttributes().IsDefaultOrEmpty)
                {
                    continue;
                }

                foreach (AttributeData ad in t.GetAttributes())
                {
                    if (ad.AttributeClass is null || !SymbolEqualityComparer.Default.Equals(ad.AttributeClass, keyAttr)
                        || ad.ConstructorArguments.Length < 1)
                    {
                        continue;
                    }

                    if (ad.ConstructorArguments[0].Value is not string value || string.IsNullOrEmpty(value))
                    {
                        continue;
                    }

                    if (valueToIdentifier.ContainsKey(value))
                    {
                        continue;
                    }

                    valueToIdentifier[value] = MakeUniqueConstIdentifier(value, usedConstNames);
                }
            }

            if (valueToIdentifier.Count == 0)
            {
                return;
            }

            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace LiveOps.Keys.Generated");
            sb.AppendLine("{");
            sb.AppendLine("  public static class LiveOpsKeys");
            sb.AppendLine("  {");
            var sorted = new List<KeyValuePair<string, string>>(valueToIdentifier);
            sorted.Sort((a, b) => string.Compare(a.Key, b.Key, StringComparison.Ordinal));
            foreach (KeyValuePair<string, string> kv in sorted)
            {
                string escaped = kv.Key.Replace(@"\", @"\\").Replace("\"", "\\\"");
                sb.Append("    public const string ").Append(kv.Value).Append(" = \"").Append(escaped).AppendLine("\";");
            }

            sb.AppendLine("  }");
            sb.AppendLine("}");
            context.AddSource("LiveOpsKeys.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void ReportWireKeyCollisionsIfAny(
            SourceProductionContext context,
            Compilation compilation,
            IReadOnlyCollection<INamedTypeSymbol> types)
        {
            INamedTypeSymbol? moduleRequest = compilation.GetTypeByMetadataName("LiveOps.DTO.ModuleRequest.ModuleRequest");
            if (moduleRequest is null)
            {
                return;
            }

            var wireToTypes = new Dictionary<string, List<INamedTypeSymbol>>(StringComparer.Ordinal);
            foreach (INamedTypeSymbol t in types)
            {
                if (t.IsAbstract || t.TypeKind is not (TypeKind.Class or TypeKind.Struct))
                {
                    continue;
                }

                string? asmName = t.ContainingAssembly.Name;
                if (asmName is not null && asmName.IndexOf("Test", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    continue;
                }

                if (!InheritsFrom(t, moduleRequest))
                {
                    continue;
                }

                string wire = ResolveWireKeyForType(compilation, t);
                if (!wireToTypes.TryGetValue(wire, out List<INamedTypeSymbol>? list))
                {
                    list = new List<INamedTypeSymbol>(2);
                    wireToTypes[wire] = list;
                }

                list.Add(t);
            }

            var duplicateWire = new DiagnosticDescriptor(
                id: "LOPSKEY001",
                title: "Duplicate GameApi wire key",
                messageFormat: "Duplicate wire key '{0}' for types: {1}",
                category: "LiveOps",
                defaultSeverity: DiagnosticSeverity.Error,
                isEnabledByDefault: true);
            foreach (KeyValuePair<string, List<INamedTypeSymbol>> kv in wireToTypes)
            {
                if (kv.Value.Count < 2)
                {
                    continue;
                }

                var names = new List<string>(kv.Value.Count);
                foreach (INamedTypeSymbol t in kv.Value)
                {
                    names.Add(t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }

                string joined = string.Join(", ", names);
                context.ReportDiagnostic(
                    Diagnostic.Create(duplicateWire, Location.None, kv.Key, joined));
            }
        }

        private static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
        {
            INamedTypeSymbol? p = type;
            while (p is not null)
            {
                if (SymbolEqualityComparer.Default.Equals(p, baseType))
                {
                    return true;
                }

                p = p.BaseType;
            }

            return false;
        }

        private static string ResolveWireKeyForType(Compilation compilation, INamedTypeSymbol t)
        {
            INamedTypeSymbol? gameApi = compilation.GetTypeByMetadataName("LiveOps.DTO.Keys.GameApiRequestAttribute");
            if (gameApi is not null)
            {
                foreach (AttributeData ad in t.GetAttributes())
                {
                    if (ad.AttributeClass is null || !SymbolEqualityComparer.Default.Equals(ad.AttributeClass, gameApi) ||
                        ad.ConstructorArguments.Length < 1)
                    {
                        continue;
                    }

                    if (ad.ConstructorArguments[0].Value is string s && !string.IsNullOrEmpty(s))
                    {
                        return s;
                    }
                }
            }

            return t.Name;
        }

        private static string MakeUniqueConstIdentifier(string value, HashSet<string> usedConstNames)
        {
            if (string.IsNullOrEmpty(value))
            {
                return TakeUnique("K_Empty", usedConstNames);
            }

            var sb = new StringBuilder(value.Length);
            for (int i = 0; i < value.Length; i++)
            {
                char c = value[i];
                if (i == 0)
                {
                    if (char.IsLetter(c) || c == '_')
                    {
                        sb.Append(c);
                    }
                    else if (char.IsDigit(c))
                    {
                        sb.Append('K').Append(c);
                    }
                    else
                    {
                        sb.Append('_');
                    }
                }
                else
                {
                    if (char.IsLetterOrDigit(c) || c == '_')
                    {
                        sb.Append(c);
                    }
                    else
                    {
                        sb.Append('_');
                    }
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("K_Value");
            }

            string baseName = sb.ToString();
            if (CSharpKeywords.Contains(baseName))
            {
                baseName = "K_" + baseName;
            }

            return TakeUnique(baseName, usedConstNames);
        }

        private static string TakeUnique(string baseName, HashSet<string> usedConstNames)
        {
            if (usedConstNames.Add(baseName))
            {
                return baseName;
            }

            for (int n = 1; n < 10_000; n++)
            {
                string alt = baseName + "_" + n;
                if (usedConstNames.Add(alt))
                {
                    return alt;
                }
            }

            return baseName + "_dup";
        }

        private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
        };

        private static bool IsRelevantRef(IAssemblySymbol a)
        {
            string? n = a.Name;
            if (string.IsNullOrEmpty(n) || n.IndexOf("Test", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return false;
            }

            return n.StartsWith("LiveOps", StringComparison.Ordinal) &&
                (n is "LiveOps.Modules" or "LiveOps.Core" or "LiveOps" or "LiveOps.DTO" or "LiveOps.Modules.DTO");
        }

        private static void VisitAssembly(IAssemblySymbol assembly, HashSet<INamedTypeSymbol> outTypes)
        {
            Visit(assembly.GlobalNamespace, outTypes);
        }

        private static void Visit(INamespaceSymbol ns, HashSet<INamedTypeSymbol> outTypes)
        {
            foreach (INamespaceSymbol child in ns.GetNamespaceMembers())
            {
                Visit(child, outTypes);
            }

            foreach (INamedTypeSymbol t in ns.GetTypeMembers())
            {
                AddNamed(t, outTypes);
            }
        }

        private static void AddNamed(INamedTypeSymbol t, HashSet<INamedTypeSymbol> outTypes)
        {
            if (t.IsStatic)
            {
                return;
            }

            if (t.TypeKind is TypeKind.Class or TypeKind.Struct)
            {
                outTypes.Add(t);
            }

            foreach (INamedTypeSymbol nested in t.GetTypeMembers())
            {
                AddNamed(nested, outTypes);
            }
        }

        private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol iface)
        {
            foreach (INamedTypeSymbol? i in type.AllInterfaces)
            {
                if (SymbolEqualityComparer.Default.Equals(i, iface) ||
                    SymbolEqualityComparer.Default.Equals(i.ConstructedFrom, iface) ||
                    SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iface.OriginalDefinition))
                {
                    return true;
                }
            }

            return false;
        }

        private static bool TryGetHandlerArgs(
            INamedTypeSymbol type,
            INamedTypeSymbol iGameHandler2Def,
            out ITypeSymbol? requestType,
            out ITypeSymbol? responseType)
        {
            requestType = null;
            responseType = null;
            foreach (INamedTypeSymbol? i in type.AllInterfaces)
            {
                if (i.IsGenericType &&
                    SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, iGameHandler2Def) &&
                    i.TypeArguments.Length == 2)
                {
                    requestType = i.TypeArguments[0];
                    responseType = i.TypeArguments[1];
                    return true;
                }
            }

            return false;
        }

        private static void EmitEmpty(SourceProductionContext context)
        {
            Emit(context, Array.Empty<Entry>());
        }

        private static void Emit(SourceProductionContext context, IReadOnlyList<Entry> entries)
        {
            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace LiveOps.Initialize");
            sb.AppendLine("{");
            sb.AppendLine("  internal static partial class LiveOpsManifest");
            sb.AppendLine("  {");
            sb.AppendLine("    private static readonly global::LiveOps.Initialize.LiveOpsManifestEntry[] _entries = new global::LiveOps.Initialize.LiveOpsManifestEntry[]");
            sb.AppendLine("    {");

            foreach (Entry e in entries)
            {
                string full = e.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (e.IsHandler && e.Req is not null && e.Res is not null)
                {
                    string reqFull = e.Req.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    string resFull = e.Res.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.Append("      new global::LiveOps.Initialize.LiveOpsManifestEntry(typeof(")
                        .Append(full)
                        .Append("), isGameApiHandler: true, isGameModule: ")
                        .Append(e.IsModule ? "true" : "false")
                        .Append(", requestType: typeof(")
                        .Append(reqFull)
                        .Append("), responseType: typeof(")
                        .Append(resFull)
                        .AppendLine(")),");
                }
                else
                {
                    sb.Append("      new global::LiveOps.Initialize.LiveOpsManifestEntry(typeof(")
                        .Append(full)
                        .Append("), isGameApiHandler: ")
                        .Append(e.IsHandler ? "true" : "false")
                        .Append(", isGameModule: ")
                        .Append(e.IsModule ? "true" : "false")
                        .AppendLine("),");
                }
            }

            sb.AppendLine("    };");
            sb.AppendLine("    public static global::System.ReadOnlySpan<global::LiveOps.Initialize.LiveOpsManifestEntry> Entries => _entries;");
            sb.AppendLine("  }");
            sb.AppendLine("}");

            context.AddSource("LiveOpsManifest.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private readonly struct Entry
        {
            public Entry(INamedTypeSymbol type, bool isHandler, bool isModule, ITypeSymbol? req, ITypeSymbol? res)
            {
                Type = type;
                IsHandler = isHandler;
                IsModule = isModule;
                Req = req;
                Res = res;
            }

            public INamedTypeSymbol Type { get; }
            public bool IsHandler { get; }
            public bool IsModule { get; }
            public ITypeSymbol? Req { get; }
            public ITypeSymbol? Res { get; }
        }
    }
}
