using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.EffectGraph.Generators
{
    [Generator]
    public sealed class EffectGraphGenerator : IIncrementalGenerator
    {
        static readonly DiagnosticDescriptor Efg001 = new(
            "EFG001",
            "Effect graph configuration required",
            "Add [assembly: EffectGraphConfig(...)] to configure effect-graph generation for this assembly.",
            "EffectGraph",
            DiagnosticSeverity.Error,
            true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(
                context.CompilationProvider,
                (spc, compilation) => Execute(spc, compilation));
        }

        static void Execute(SourceProductionContext spc, Compilation compilation)
        {
            INamedTypeSymbol? cfgSym =
                compilation.GetTypeByMetadataName("Scaffold.EffectGraph.EffectGraphConfigAttribute");
            INamedTypeSymbol? skipSym =
                compilation.GetTypeByMetadataName("Scaffold.EffectGraph.EffectGraphSkipGenerationAttribute");
            if (cfgSym is null)
                return;

            if (!ReferencesEffectGraphAttributes(compilation))
                return;

            if (HasSkipAttribute(compilation.Assembly, skipSym))
                return;

            AttributeData? configAttr = null;
            foreach (AttributeData attr in compilation.Assembly.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attr.AttributeClass, cfgSym))
                {
                    configAttr = attr;
                    break;
                }
            }

            if (configAttr is null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(Efg001, Location.None));
                return;
            }

            var commandBases = GetStringArray(configAttr, "CommandBases");
            var entryBases = GetStringArray(configAttr, "EntryBases");
            string registryNs = GetNamedString(configAttr, "RegistryNamespace") ?? "";
            if (registryNs.Length == 0 || commandBases.Length + entryBases.Length == 0)
            {
                spc.ReportDiagnostic(Diagnostic.Create(Efg001, Location.None));
                return;
            }

            var asm = compilation.Assembly;
            var entryRoots = entryBases
                .Select(compilation.GetTypeByMetadataName)
                .Where(t => t is not null)
                .Cast<INamedTypeSymbol>()
                .ToList();

            var entryTypes = new List<INamedTypeSymbol>();
            foreach (INamedTypeSymbol root in entryRoots)
                CollectConcreteSubtypes(asm, root, entryTypes);

            Emit(spc, registryNs, entryTypes);
        }

        static bool ReferencesEffectGraphAttributes(Compilation compilation)
        {
            foreach (MetadataReference reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol asm)
                    continue;
                if (string.Equals(asm.Name, "Scaffold.EffectGraph.Attributes", StringComparison.Ordinal))
                    return true;
            }

            return false;
        }

        static bool HasSkipAttribute(IAssemblySymbol asm, INamedTypeSymbol? skipSym)
        {
            if (skipSym is null)
                return false;
            foreach (AttributeData attr in asm.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attr.AttributeClass, skipSym))
                    return true;
            }

            return false;
        }

        static void Emit(SourceProductionContext spc, string registryNs, List<INamedTypeSymbol> entryTypes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Unity.GraphToolkit.Editor;");
            sb.AppendLine("using Scaffold.EffectGraph.Editor;");
            sb.AppendLine();
            sb.AppendLine($"namespace {registryNs}");
            sb.AppendLine("{");

            foreach (INamedTypeSymbol et in entryTypes.OrderBy(s => s.ToDisplayString()))
            {
                string safe = Sanitize(et.Name);
                sb.AppendLine($"    [Serializable]");
                sb.AppendLine($"    internal sealed class On{safe}EntryNode : Node");
                sb.AppendLine("    {");
                sb.AppendLine("        protected override void OnDefinePorts(IPortDefinitionContext context)");
                sb.AppendLine("        {");
                sb.AppendLine(
                    "            context.AddOutputPort(\"Run\").WithConnectorUI(PortConnectorUI.Arrowhead).Build();");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
                var fqEditor = $"{registryNs}.On{safe}EntryNode";
                sb.AppendLine(
                    $"    internal static partial class EffectRegistry {{ public const string TypeId_{safe} = \"{fqEditor}\"; }}");
                sb.AppendLine();
            }

            sb.AppendLine("    internal static class EffectRegistryInitializer");
            sb.AppendLine("    {");
            sb.AppendLine("        internal static void RegisterAll()");
            sb.AppendLine("        {");
            sb.AppendLine("            EffectGraphRegistry.Clear();");
            foreach (INamedTypeSymbol et in entryTypes.OrderBy(s => s.ToDisplayString()))
            {
                string safe = Sanitize(et.Name);
                sb.AppendLine(
                    $"            EffectGraphRegistry.Register(EffectRegistry.TypeId_{safe}, typeof(On{safe}EntryNode));");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("EffectGraph.GeneratedNodes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

            var initSb = new StringBuilder();
            initSb.AppendLine("// <auto-generated />");
            initSb.AppendLine("#nullable enable");
            initSb.AppendLine("using Scaffold.EffectGraph.Editor;");
            initSb.AppendLine();
            initSb.AppendLine($"namespace {registryNs}");
            initSb.AppendLine("{");
            initSb.AppendLine("    internal static class EffectGraphGeneratedModuleInitializer");
            initSb.AppendLine("    {");
            initSb.AppendLine("        [global::UnityEditor.InitializeOnLoadMethod]");
            initSb.AppendLine("        private static void Init()");
            initSb.AppendLine("        {");
            initSb.AppendLine("            EffectRegistryInitializer.RegisterAll();");
            initSb.AppendLine("        }");
            initSb.AppendLine("    }");
            initSb.AppendLine("}");
            spc.AddSource("EffectGraph.GeneratedInit.g.cs", SourceText.From(initSb.ToString(), Encoding.UTF8));
        }

        static string Sanitize(string name)
        {
            var chars = name.ToCharArray();
            for (int i = 0; i < chars.Length; i++)
            {
                if (!char.IsLetterOrDigit(chars[i]))
                    chars[i] = '_';
            }

            return new string(chars);
        }

        static string[] GetStringArray(AttributeData attr, string name)
        {
            foreach (KeyValuePair<string, TypedConstant> pair in attr.NamedArguments)
            {
                if (pair.Key != name)
                    continue;
                TypedConstant c = pair.Value;
                if (c.Kind != TypedConstantKind.Array)
                    return Array.Empty<string>();
                ImmutableArray<TypedConstant> items = c.Values;
                var list = new string[items.Length];
                for (int i = 0; i < items.Length; i++)
                    list[i] = items[i].Value?.ToString() ?? "";
                return list;
            }

            return Array.Empty<string>();
        }

        static string? GetNamedString(AttributeData attr, string name)
        {
            foreach (KeyValuePair<string, TypedConstant> pair in attr.NamedArguments)
            {
                if (pair.Key == name && pair.Value.Value is string s)
                    return s;
            }

            return null;
        }

        static void CollectConcreteSubtypes(IAssemblySymbol assembly, INamedTypeSymbol root,
            List<INamedTypeSymbol> bag)
        {
            void VisitNamespace(INamespaceSymbol ns)
            {
                foreach (INamespaceSymbol child in ns.GetNamespaceMembers())
                    VisitNamespace(child);
                foreach (INamedTypeSymbol type in ns.GetTypeMembers())
                    VisitType(type);
            }

            void VisitType(INamedTypeSymbol type)
            {
                if (type.TypeKind == TypeKind.Class && !type.IsAbstract && InheritsFrom(type, root))
                    bag.Add(type);
                foreach (INamedTypeSymbol nested in type.GetTypeMembers())
                    VisitType(nested);
            }

            VisitNamespace(assembly.GlobalNamespace);
        }

        static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol root)
        {
            INamedTypeSymbol rootDef = root.IsGenericType ? root.OriginalDefinition : root;
            for (INamedTypeSymbol? b = type.BaseType; b is not null; b = b.BaseType)
            {
                INamedTypeSymbol bDef = b.IsGenericType ? b.OriginalDefinition : b;
                if (SymbolEqualityComparer.Default.Equals(bDef, rootDef))
                    return true;
            }

            return false;
        }
    }
}
