// <auto-generated />
// Run: dotnet build Generators/GraphFlowGenerator -c Release to refresh from Scaffold.GraphFlowGenerator when definitions change.
#nullable enable

namespace Scaffold.GraphFlow.Sample
{
    partial class AddNumbersDefinition
    {
        public override string DefinitionTypeId => "Scaffold.GraphFlow.Sample.AddNumbersDefinition";
    }

    partial class MultiplyAddInputsDefinition
    {
        public override string DefinitionTypeId => "Scaffold.GraphFlow.Sample.MultiplyAddInputsDefinition";
    }

    partial class LogObjectDefinition
    {
        public override string DefinitionTypeId => "Scaffold.GraphFlow.Sample.LogObjectDefinition";
    }

    partial class InvokeSubGraphDefinition
    {
        public override string DefinitionTypeId => "Scaffold.GraphFlow.Sample.InvokeSubGraphDefinition";
    }

    partial class GraphFlowEntryPassThroughDefinition
    {
        public override string DefinitionTypeId => "Scaffold.GraphFlow.Sample.GraphFlowEntryPassThroughDefinition";
    }
}

namespace Scaffold.GraphFlow.Generated
{
    public static class GraphFlowGeneratedRegistration
    {
        public static void RegisterAll(GraphFlowRegistry registry)
        {
            registry.Register(new Scaffold.GraphFlow.Sample.AddNumbersDefinition());
            registry.Register(new Scaffold.GraphFlow.Sample.MultiplyAddInputsDefinition());
            registry.Register(new Scaffold.GraphFlow.Sample.LogObjectDefinition());
            registry.Register(new Scaffold.GraphFlow.Sample.InvokeSubGraphDefinition());
            registry.Register(new Scaffold.GraphFlow.Sample.GraphFlowEntryPassThroughDefinition());
        }
    }
}
