using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Emits the per-package <c>&lt;Stem&gt;Catalog</c> — a generator-driven static catalog of
    /// every type the framework cares about (events, return types, commands, entry payloads).
    /// Replaces the scattered switch statements / per-feature lists with a single uniform
    /// data structure that editor mirrors and bake factories index into.
    ///
    /// <para>Per-concern picker enums are emitted alongside the entries because GraphToolkit's
    /// <c>AddOption&lt;TEnum&gt;</c> dropdown shows all values of TEnum unfiltered — a single
    /// catalog-wide enum would mix unrelated kinds. Each picker enum gets its own narrow dropdown
    /// while sharing the same underlying <see cref="CatalogEntry"/> payloads.</para>
    /// </summary>
    internal static class GraphCatalogEmitter
    {
        internal const string CatalogClassSuffix = "Catalog";

        internal sealed class EventDescriptor
        {
            internal INamedTypeSymbol Type { get; }
            internal IReadOnlyList<IFieldSymbol> Fields { get; }
            internal EventDescriptor(INamedTypeSymbol type, IReadOnlyList<IFieldSymbol> fields)
            { Type = type; Fields = fields; }
        }

        internal sealed class CommandDescriptor
        {
            internal INamedTypeSymbol Command { get; }
            internal INamedTypeSymbol Result { get; }
            internal IReadOnlyList<IFieldSymbol> Inputs { get; }
            internal IReadOnlyList<IFieldSymbol> Outputs { get; }
            internal string DispatcherRuntimeFq { get; }
            internal CommandDescriptor(INamedTypeSymbol cmd, INamedTypeSymbol res,
                IReadOnlyList<IFieldSymbol> inputs, IReadOnlyList<IFieldSymbol> outputs,
                string dispatcherRuntimeFq)
            { Command = cmd; Result = res; Inputs = inputs; Outputs = outputs; DispatcherRuntimeFq = dispatcherRuntimeFq; }
        }

        internal sealed class EntryDescriptor
        {
            internal INamedTypeSymbol Type { get; }
            internal IReadOnlyList<IFieldSymbol> Fields { get; }
            internal string RuntimeFq { get; }
            internal EntryDescriptor(INamedTypeSymbol type, IReadOnlyList<IFieldSymbol> fields, string runtimeFq)
            { Type = type; Fields = fields; RuntimeFq = runtimeFq; }
        }

        internal sealed class ReturnDescriptor
        {
            /// <summary>Display label used as the enum value name (e.g. "Int", "Bool", "DamageDealt").</summary>
            internal string Label { get; }
            /// <summary>Fully-qualified C# type expression (e.g. "int", "bool", "global::MyApp.MyType").</summary>
            internal string TypeFq { get; }
            internal string DefaultLiteral { get; }
            internal ReturnDescriptor(string label, string typeFq, string defaultLiteral)
            { Label = label; TypeFq = typeFq; DefaultLiteral = defaultLiteral; }
        }

        /// <summary>
        /// Emits a single <c>&lt;Stem&gt;Catalog</c> static class into the package's runtime asm.
        /// Called only on the runtime-asm pass (editor pass uses the same catalog by reference).
        /// </summary>
        internal static void EmitRuntimeCatalog(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            IReadOnlyList<EventDescriptor> events,
            IReadOnlyList<CommandDescriptor> commands,
            IReadOnlyList<EntryDescriptor> entries,
            IReadOnlyList<ReturnDescriptor> returns)
        {
            var ns = ResolveCatalogNamespace(package, compilation);
            var typeName = package.GraphStem + CatalogClassSuffix;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Scaffold.GraphFlow;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {typeName}");
            sb.AppendLine("    {");

            EmitEntries(sb, package, events, commands, entries, returns);
            EmitIndex(sb, events, commands, entries, returns);
            EmitEventPortUnions(sb, events);
            EmitChoiceEnums(sb, events, commands, entries, returns);
            EmitResolvers(sb, events, commands, entries, returns);

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        internal static string ResolveCatalogNamespace(GraphPackageModel package, Compilation compilation)
        {
            // Same convention as the registry — emit into <RootNamespace>.Generated when the
            // user hasn't supplied a custom RegistryNamespace.
            if (!string.IsNullOrEmpty(package.RegistryNamespace))
            {
                return package.RegistryNamespace;
            }

            return GraphCompilationNames.EditorPackageRoot(compilation) + ".Generated";
        }

        // ============ ENTRIES ============

        static void EmitEntries(
            StringBuilder sb,
            GraphPackageModel package,
            IReadOnlyList<EventDescriptor> events,
            IReadOnlyList<CommandDescriptor> commands,
            IReadOnlyList<EntryDescriptor> entries,
            IReadOnlyList<ReturnDescriptor> returns)
        {
            sb.AppendLine("        // ============ Entries (uniform shape, Kinds discriminator) ============");
            sb.AppendLine();

            foreach (var e in events)
            {
                EmitEventEntry(sb, e);
            }

            foreach (var c in commands)
            {
                EmitCommandEntry(sb, c);
            }

            foreach (var e in entries)
            {
                EmitEntryEntry(sb, e);
            }

            foreach (var r in returns)
            {
                EmitReturnEntry(sb, r);
            }
        }

        static void EmitEventEntry(StringBuilder sb, EventDescriptor e)
        {
            var fieldName = e.Type.Name;
            var typeFq = TrimGlobal(e.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.AppendLine($"        public static readonly CatalogEntry {fieldName} = new(");
            sb.AppendLine($"            kinds: CatalogKind.Event,");
            sb.AppendLine($"            type:  typeof({typeFq}),");
            EmitEventPortsArray(sb, e.Fields, "            ");
            sb.AppendLine($",");
            sb.AppendLine($"            createRuntime: () => new global::Scaffold.GraphFlow.OnTrigger<{typeFq}>()");
            sb.AppendLine($"        );");
            sb.AppendLine();
        }

        static void EmitCommandEntry(StringBuilder sb, CommandDescriptor c)
        {
            var fieldName = c.Command.Name;
            var typeFq    = TrimGlobal(c.Command.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            var resultFq  = TrimGlobal(c.Result.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.AppendLine($"        public static readonly CatalogEntry {fieldName} = new(");
            sb.AppendLine($"            kinds: CatalogKind.Command,");
            sb.AppendLine($"            type:  typeof({typeFq}),");
            EmitCommandPortsArray(sb, c.Inputs, c.Outputs, "            ");
            sb.AppendLine($",");
            sb.AppendLine($"            createRuntime: () => new {c.DispatcherRuntimeFq}(),");
            sb.AppendLine($"            resultType:    typeof({resultFq})");
            sb.AppendLine($"        );");
            sb.AppendLine();
        }

        static void EmitEntryEntry(StringBuilder sb, EntryDescriptor e)
        {
            var fieldName = e.Type.Name;
            var typeFq    = TrimGlobal(e.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            sb.AppendLine($"        public static readonly CatalogEntry {fieldName} = new(");
            sb.AppendLine($"            kinds: CatalogKind.Entry,");
            sb.AppendLine($"            type:  typeof({typeFq}),");
            EmitEventPortsArray(sb, e.Fields, "            ");
            sb.AppendLine($",");
            sb.AppendLine($"            createRuntime: () => new {e.RuntimeFq}()");
            sb.AppendLine($"        );");
            sb.AppendLine();
        }

        static void EmitReturnEntry(StringBuilder sb, ReturnDescriptor r)
        {
            sb.AppendLine($"        public static readonly CatalogEntry {r.Label} = new(");
            sb.AppendLine($"            kinds: CatalogKind.Return,");
            sb.AppendLine($"            type:  typeof({r.TypeFq}),");
            sb.AppendLine($"            ports: System.Array.Empty<PortMeta>(),");
            sb.AppendLine($"            createRuntime:  () => new global::Scaffold.GraphFlow.Nodes.Return<{r.TypeFq}>(),");
            sb.AppendLine($"            defaultLiteral: \"{EscapeStringLiteral(r.DefaultLiteral)}\"");
            sb.AppendLine($"        );");
            sb.AppendLine();
        }

        static void EmitEventPortsArray(StringBuilder sb, IReadOnlyList<IFieldSymbol> fields, string indent)
        {
            if (fields.Count == 0)
            {
                sb.Append($"{indent}ports: System.Array.Empty<PortMeta>()");
                return;
            }

            sb.AppendLine($"{indent}ports: new[]");
            sb.AppendLine($"{indent}{{");
            foreach (var f in fields)
            {
                var fTypeFq = TrimGlobal(f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                // Two ports per event field — read (output) and write (input) — for Option F payload mutation.
                sb.AppendLine($"{indent}    new PortMeta(\"{f.Name}\", typeof({fTypeFq}), PortDirection.Output),");
                sb.AppendLine($"{indent}    new PortMeta(\"{f.Name}\", typeof({fTypeFq}), PortDirection.Input),");
            }

            sb.Append($"{indent}}}");
        }

        static void EmitCommandPortsArray(StringBuilder sb, IReadOnlyList<IFieldSymbol> inputs, IReadOnlyList<IFieldSymbol> outputs, string indent)
        {
            if (inputs.Count == 0 && outputs.Count == 0)
            {
                sb.Append($"{indent}ports: System.Array.Empty<PortMeta>()");
                return;
            }

            sb.AppendLine($"{indent}ports: new[]");
            sb.AppendLine($"{indent}{{");
            foreach (var f in inputs)
            {
                var fTypeFq = TrimGlobal(f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                sb.AppendLine($"{indent}    new PortMeta(\"{f.Name}\", typeof({fTypeFq}), PortDirection.Input),");
            }

            foreach (var f in outputs)
            {
                var fTypeFq = TrimGlobal(f.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                sb.AppendLine($"{indent}    new PortMeta(\"{f.Name}\", typeof({fTypeFq}), PortDirection.Output),");
            }

            sb.Append($"{indent}}}");
        }

        // ============ INDEX ============

        static void EmitIndex(
            StringBuilder sb,
            IReadOnlyList<EventDescriptor> events,
            IReadOnlyList<CommandDescriptor> commands,
            IReadOnlyList<EntryDescriptor> entries,
            IReadOnlyList<ReturnDescriptor> returns)
        {
            sb.AppendLine("        // ============ Index ============");
            sb.AppendLine();
            sb.AppendLine("        static readonly CatalogEntry[] s_All =");
            sb.AppendLine("        {");

            foreach (var e in events)
            {
                sb.AppendLine($"            {e.Type.Name},");
            }

            foreach (var c in commands)
            {
                sb.AppendLine($"            {c.Command.Name},");
            }

            foreach (var e in entries)
            {
                sb.AppendLine($"            {e.Type.Name},");
            }

            foreach (var r in returns)
            {
                sb.AppendLine($"            {r.Label},");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static IReadOnlyList<CatalogEntry> All => s_All;");
            sb.AppendLine();
            sb.AppendLine("        public static IEnumerable<CatalogEntry> OfKind(CatalogKind k) =>");
            sb.AppendLine("            s_All.Where(e => (e.Kinds & k) != 0);");
            sb.AppendLine();
            sb.AppendLine("        public static CatalogEntry? Get(System.Type t) =>");
            sb.AppendLine("            s_All.FirstOrDefault(e => e.Type == t);");
            sb.AppendLine();
        }

        // ============ EVENT PORT UNIONS ============
        // The union of every [GraphEvent]'s field names per direction. The single-instance
        // OnTrigger node registration uses these for its data port name sets so the EFG-V03
        // edge-pairing validator can recognize wires from/to the dynamically-emitted event-field
        // ports. Union-not-per-event is fine: the editor only adds ports for the picked event,
        // so V03 only sees names that actually exist on that event.

        static void EmitEventPortUnions(StringBuilder sb, IReadOnlyList<EventDescriptor> events)
        {
            sb.AppendLine("        // ============ Event port unions (for V03 edge validation) ============");
            sb.AppendLine();

            var outputs = new HashSet<string>(System.StringComparer.Ordinal);
            var inputs  = new HashSet<string>(System.StringComparer.Ordinal);
            foreach (var e in events)
            {
                foreach (var f in e.Fields)
                {
                    // Match the per-entry port emission: each event field surfaces as both an
                    // output (read) and an input (write) port — Option F payload mutation.
                    outputs.Add(f.Name);
                    inputs.Add(f.Name);
                }
            }

            EmitStringList(sb, "AllEventDataOutputPortNames", outputs);
            EmitStringList(sb, "AllEventDataInputPortNames",  inputs);
        }

        static void EmitStringList(StringBuilder sb, string name, IEnumerable<string> values)
        {
            sb.AppendLine($"        public static readonly System.Collections.Generic.IReadOnlyList<string> {name} = new string[]");
            sb.AppendLine("        {");
            foreach (var v in values)
            {
                sb.AppendLine($"            \"{EscapeStringLiteral(v)}\",");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // ============ CHOICE ENUMS ============

        static void EmitChoiceEnums(
            StringBuilder sb,
            IReadOnlyList<EventDescriptor> events,
            IReadOnlyList<CommandDescriptor> commands,
            IReadOnlyList<EntryDescriptor> entries,
            IReadOnlyList<ReturnDescriptor> returns)
        {
            sb.AppendLine("        // ============ Per-concern picker enums ============");
            sb.AppendLine("        // GraphToolkit's AddOption<TEnum> shows all values unfiltered — one enum per concern");
            sb.AppendLine("        // keeps each picker dropdown scoped to its semantic role.");
            sb.AppendLine();

            EmitChoiceEnum(sb, "EventType", GetEventLabels(events));
            EmitChoiceEnum(sb, "ReturnType", GetReturnLabels(returns));
            EmitChoiceEnum(sb, "CommandType", GetCommandLabels(commands));
            EmitChoiceEnum(sb, "EntryType", GetEntryLabels(entries));
        }

        static void EmitChoiceEnum(StringBuilder sb, string enumName, IReadOnlyList<string> labels)
        {
            sb.AppendLine($"        public enum {enumName}");
            sb.AppendLine("        {");
            sb.AppendLine("            None = 0,");
            for (var i = 0; i < labels.Count; i++)
            {
                sb.AppendLine($"            {labels[i]} = {i + 1},");
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ============ RESOLVERS ============

        static void EmitResolvers(
            StringBuilder sb,
            IReadOnlyList<EventDescriptor> events,
            IReadOnlyList<CommandDescriptor> commands,
            IReadOnlyList<EntryDescriptor> entries,
            IReadOnlyList<ReturnDescriptor> returns)
        {
            sb.AppendLine("        // ============ Resolve ============");
            sb.AppendLine();

            EmitResolver(sb, "EventType", GetEventLabels(events), e => e);
            EmitResolver(sb, "ReturnType", GetReturnLabels(returns), e => e);
            EmitResolver(sb, "CommandType", GetCommandLabels(commands), e => e);
            EmitResolver(sb, "EntryType", GetEntryLabels(entries), e => e);
        }

        static void EmitResolver(StringBuilder sb, string enumName, IReadOnlyList<string> labels, System.Func<string, string> labelToFieldName)
        {
            sb.AppendLine($"        public static CatalogEntry? Resolve({enumName} c) => c switch");
            sb.AppendLine("        {");
            foreach (var l in labels)
            {
                sb.AppendLine($"            {enumName}.{l} => {labelToFieldName(l)},");
            }

            sb.AppendLine($"            _ => null,");
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // ============ HELPERS ============

        static IReadOnlyList<string> GetEventLabels(IReadOnlyList<EventDescriptor> events)
        {
            var list = new List<string>(events.Count);
            foreach (var e in events) list.Add(e.Type.Name);
            return list;
        }

        static IReadOnlyList<string> GetReturnLabels(IReadOnlyList<ReturnDescriptor> returns)
        {
            var list = new List<string>(returns.Count);
            foreach (var r in returns) list.Add(r.Label);
            return list;
        }

        static IReadOnlyList<string> GetCommandLabels(IReadOnlyList<CommandDescriptor> commands)
        {
            var list = new List<string>(commands.Count);
            foreach (var c in commands) list.Add(c.Command.Name);
            return list;
        }

        static IReadOnlyList<string> GetEntryLabels(IReadOnlyList<EntryDescriptor> entries)
        {
            var list = new List<string>(entries.Count);
            foreach (var e in entries) list.Add(e.Type.Name);
            return list;
        }

        static string TrimGlobal(string fq)
        {
            return fq.StartsWith("global::", System.StringComparison.Ordinal) ? fq.Substring(8) : fq;
        }

        static string EscapeStringLiteral(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
