using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    [Generator]
    public sealed class GraphNodeRuntimePartialGenerator : IIncrementalGenerator
    {
        const string GraphNodeAttrFqn = "Scaffold.GraphFlow.GraphNodeAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var nodes = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GraphNodeAttrFqn,
                    static (s, _) => s is ClassDeclarationSyntax,
                    static (ctx, _) => ctx.TargetSymbol as INamedTypeSymbol)
                .Where(static s => s != null);

            context.RegisterSourceOutput(nodes, static (spc, type) =>
            {
                if (type != null) EmitForType(spc, type);
            });
        }

        static void EmitForType(SourceProductionContext spc, INamedTypeSymbol type)
        {
            if (type.TypeKind != TypeKind.Class) return;
            if (type.IsAbstract || type.DeclaredAccessibility != Accessibility.Public) return;
            if (type.TypeParameters.Length > 1) return;

            var isGenericOverRunner = type.TypeParameters.Length == 1 && IsGenericOverRunner(type);
            if (type.TypeParameters.Length == 1 && !isGenericOverRunner) return;

            var inputs = new List<(string name, string csType)>();
            var outputs = new List<(string name, string csType)>();
            var flowIns = new List<string>();
            var flowOuts = new List<string>();

            foreach (var member in type.GetMembers())
            {
                if (member is not IFieldSymbol field || field.IsStatic) continue;
                if (field.Type is not INamedTypeSymbol typed) continue;

                if (typed.Name == "InputPort" && typed.TypeArguments.Length == 1)
                {
                    inputs.Add((field.Name, TypeFmt.Simple(typed.TypeArguments[0])));
                }
                else if (typed.Name == "OutputPort" && typed.TypeArguments.Length == 1)
                {
                    outputs.Add((field.Name, TypeFmt.Simple(typed.TypeArguments[0])));
                }
                else if (typed.Name == "FlowOutPort")
                {
                    flowOuts.Add(field.Name);
                }
                else if (typed.Name == "FlowInPort")
                {
                    flowIns.Add(field.Name);
                }
            }

            var hasInitHook = type.GetMembers("InitializePorts").OfType<IMethodSymbol>().Any();
            // The partial calls InitializePorts() whenever the user owns
            // construction of any port — outputs (typed lambdas) or flow-ins
            // (handler-required FlowInPort.Sync / FlowInPort.Async). The
            // partial only emits the declaration, the user provides the body.
            var needsInitCall = hasInitHook || outputs.Count > 0 || flowIns.Count > 0;

            var sb = new StringBuilder();
            var ns = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Scaffold.GraphFlow;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }

            var typeHeader = isGenericOverRunner
                ? $"    partial class {type.Name}<{type.TypeParameters[0].Name}>"
                : $"    partial class {type.Name}";
            sb.AppendLine(typeHeader);
            sb.AppendLine("    {");
            sb.AppendLine($"        public {type.Name}()");
            sb.AppendLine("        {");

            foreach (var p in inputs)
            {
                sb.AppendLine($"            {p.name} = new InputPort<{p.csType}>();");
            }

            foreach (var name in flowOuts)
            {
                sb.AppendLine($"            {name} = new FlowOutPort(this, \"{name}\");");
            }

            if (needsInitCall)
            {
                sb.AppendLine("            InitializePorts();");
            }

            foreach (var p in inputs)
            {
                sb.AppendLine($"            Ports.Add(\"{p.name}\", {p.name});");
            }

            foreach (var p in outputs)
            {
                sb.AppendLine($"            Ports.Add(\"{p.name}\", {p.name});");
            }

            foreach (var name in flowIns)
            {
                sb.AppendLine($"            Ports.Add({name}.Name, {name});");
            }

            foreach (var name in flowOuts)
            {
                sb.AppendLine($"            Ports.Add({name}.Name, {name});");
            }

            sb.AppendLine("        }");

            if (needsInitCall)
            {
                sb.AppendLine();
                sb.AppendLine("        partial void InitializePorts();");
            }

            sb.AppendLine("    }");
            if (!string.IsNullOrEmpty(ns))
            {
                sb.AppendLine("}");
            }

            spc.AddSource($"{type.Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static bool IsGenericOverRunner(INamedTypeSymbol type)
        {
            for (var current = type.BaseType; current != null; current = current.BaseType)
            {
                if (current.MetadataName == "RuntimeNode`1")
                {
                    return true;
                }
            }
            return false;
        }
    }
}
