using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Emits the runtime partial (default ctor that constructs typed port handles + populates the
    /// <c>Ports</c> dict) plus the editor mirror + per-package registry entry for hand-written
    /// <c>[GraphNode]</c> classes. Author writes only the typed surface — port-handle fields and
    /// (for flow nodes) the <c>Execute</c> body, plus an optional <c>partial void InitializePorts()</c>
    /// for OutputPort assignment.
    ///
    /// <para>See ExecPlan-v2.md "Generic-node emission" for the full surface + design-iteration log.</para>
    /// </summary>
    internal static class GraphGenericNodeEmitter
    {
        internal static void EmitForPackage(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            ImmutableArray<GenericNodeModel> nodes,
            List<string>? registrationBlocks,
            bool editorAssembly)
        {
            if (nodes.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (var node in nodes)
            {
                if (editorAssembly)
                {
                    EmitEditorMirror(spc, compilation, node);
                    registrationBlocks?.Add(BuildRegistrationBlock(package, compilation, node));
                }
                else
                {
                    // Runtime partial completes the hand-written class with the default ctor + dict
                    // population. Emitted only in the runtime asm pass (where the runtime class lives).
                    EmitRuntimePartial(spc, package, node);
                }
            }
        }

        static void EmitRuntimePartial(SourceProductionContext spc, GraphPackageModel package, GenericNodeModel node)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Scaffold.GraphFlow;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(node.TypeNamespace))
            {
                sb.AppendLine($"namespace {node.TypeNamespace}");
                sb.AppendLine("{");
            }

            var typeHeader = node.IsGenericOverRunner
                ? $"    partial class {node.TypeName}<TRunner>"
                : $"    partial class {node.TypeName}";
            sb.AppendLine(typeHeader);
            sb.AppendLine("    {");
            sb.AppendLine($"        public {node.TypeName}()");
            sb.AppendLine("        {");

            // Construct InputPort<T> fields with no fallback (defaults to default(T)). Author can
            // override defaults via field initializers in their hand-written file if needed.
            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            {p.FieldName} = new InputPort<{p.CSharpType}>();");
            }

            // FlowOut struct was removed in M3 (D3). Authoring nodes now call `flow.GoTo(portId)`
            // directly with the int port id. If a [GraphNode] still declares `FlowOut` fields we
            // emit nothing for them here — the field type itself is gone, so author code referring
            // to it won't compile, which is the desired loud failure.
            // (Generator scaffolding for FlowOut emission removed alongside the struct.)

            // OutputPort assignment is the user's responsibility (the reader closes over typed inputs)
            // — invoked through the partial method hook. If the class has no OutputPort fields and the
            // user didn't declare InitializePorts, the hook is absent and we skip the call.
            if (node.HasInitializePortsHook || node.Outputs.Length > 0)
            {
                sb.AppendLine("            InitializePorts();");
            }

            // Populate Ports dict — input + output handles only. FlowOut and the implicit FlowIn
            // (for flow nodes) are not in the data-port dict; flow wiring goes through flowEdges.
            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            Ports.Add({GraphRegistryEmitter.PortIdLiteral(p.PortId)}, {p.FieldName});");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"            Ports.Add({GraphRegistryEmitter.PortIdLiteral(p.PortId)}, {p.FieldName});");
            }

            sb.AppendLine("        }");

            // Declare InitializePorts as partial when there are output ports (the user implements it).
            // Skip when the user has no outputs to wire — keeps the .g.cs minimal.
            if (node.Outputs.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        partial void InitializePorts();");
            }

            sb.AppendLine("    }");
            if (!string.IsNullOrEmpty(node.TypeNamespace))
            {
                sb.AppendLine("}");
            }

            spc.AddSource($"{node.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static void EmitEditorMirror(SourceProductionContext spc, Compilation compilation, GenericNodeModel node)
        {
            var editorNs = GraphCompilationNames.EditorGraphToolkitNamespace(compilation);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Unity.GraphToolkit.Editor;");
            sb.AppendLine();
            sb.AppendLine($"namespace {editorNs}");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {node.TypeName}EditorNode : Node");
            sb.AppendLine("    {");
            // Port-name consts (used by the registry's port-name → port-id maps).
            if (node.IsFlowNode)
            {
                sb.AppendLine("        public const string FlowInPortName = \"FlowIn\";");
            }

            foreach (var p in node.FlowOuts)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            sb.AppendLine();
            sb.AppendLine("        protected override void OnDefinePorts(IPortDefinitionContext context)");
            sb.AppendLine("        {");
            if (node.IsFlowNode)
            {
                sb.AppendLine("            context.AddInputPort(FlowInPortName)");
                sb.AppendLine("                .WithDisplayName(string.Empty)");
                sb.AppendLine("                .WithConnectorUI(PortConnectorUI.Arrowhead)");
                sb.AppendLine("                .Build();");
            }

            foreach (var p in node.FlowOuts)
            {
                sb.AppendLine($"            context.AddOutputPort({p.FieldName}PortName)");
                sb.AppendLine($"                .WithDisplayName(\"{p.FieldName}\")");
                sb.AppendLine("                .WithConnectorUI(PortConnectorUI.Arrowhead)");
                sb.AppendLine("                .Build();");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            context.AddInputPort<{p.CSharpType}>({p.FieldName}PortName).Build();");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"            context.AddOutputPort<{p.CSharpType}>({p.FieldName}PortName).Build();");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{node.TypeName}EditorNode.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static string BuildRegistrationBlock(GraphPackageModel package, Compilation compilation, GenericNodeModel node)
        {
            var runnerFq = GraphRegistryEmitter.TrimGlobal(package.RunnerFullyQualified);
            var editorTypeFq = GraphCompilationNames.EditorGraphToolkitNamespace(compilation) + "." + node.TypeName + "EditorNode";
            var runtimeTypeFq = ClosedRuntimeTypeFq(package, node);

            var dataInputs = ToInputTriples(node.Inputs);
            var dataOutputs = ToOutputPairs(node.Outputs);

            if (!node.IsFlowNode)
            {
                return GraphRegistryEmitter.BuildDataNodeRegistrationBlock(runnerFq, editorTypeFq, runtimeTypeFq, dataInputs, dataOutputs);
            }

            var flowOutPairs = new List<(string, int)>();
            foreach (var p in node.FlowOuts)
            {
                flowOutPairs.Add((p.FieldName, p.PortId));
            }

            return GraphRegistryEmitter.BuildFlowNodeRegistrationBlock(runnerFq, editorTypeFq, runtimeTypeFq, node.ImplicitFlowInPortId, flowOutPairs, dataInputs, dataOutputs);
        }

        static string ClosedRuntimeTypeFq(GraphPackageModel package, GenericNodeModel node)
        {
            var fqNoGeneric = node.FullyQualifiedNoGeneric;
            return node.IsGenericOverRunner
                ? fqNoGeneric + "<" + GraphRegistryEmitter.TrimGlobal(package.RunnerFullyQualified) + ">"
                : fqNoGeneric;
        }

        static List<(string Name, int Id, string CSharpType)> ToInputTriples(ImmutableArray<GenericNodeInputField> inputs)
        {
            var list = new List<(string, int, string)>();
            foreach (var p in inputs)
            {
                list.Add((p.FieldName, p.PortId, p.CSharpType));
            }

            return list;
        }

        static List<(string Name, int Id)> ToOutputPairs(ImmutableArray<GenericNodeOutputField> outputs)
        {
            var list = new List<(string, int)>();
            foreach (var p in outputs)
            {
                list.Add((p.FieldName, p.PortId));
            }

            return list;
        }
    }
}
