using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Emits the runtime partial (default ctor that constructs typed port handles + populates the
    /// <c>Ports</c> dict) plus the editor mirror + per-package registry entry for hand-written
    /// <c>[GraphNode]</c> classes.
    /// </summary>
    internal static class GraphGenericNodeEmitter
    {
        internal static void EmitForPackage(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            ImmutableArray<GenericNodeModel> nodes,
            HashSet<string> sourcedInCurrentCompilation,
            List<string>? registrationBlocks,
            bool editorAssembly)
        {
            if (nodes.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (var node in nodes)
            {
                if (editorAssembly)
                {
                    EmitEditorMirror(spc, compilation, node);
                    registrationBlocks?.Add(BuildRegistrationBlock(package, compilation, node));
                }
                else
                {
                    var key = (node.TypeNamespace ?? "") + "." + node.TypeName;
                    if (sourcedInCurrentCompilation.Contains(key))
                    {
                        EmitRuntimePartial(spc, package, node);
                    }
                }
            }
        }

        static void EmitRuntimePartial(SourceProductionContext spc, GraphPackageModel package, GenericNodeModel node)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Scaffold.GraphFlow;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(node.TypeNamespace))
            {
                sb.AppendLine($"namespace {node.TypeNamespace}");
                sb.AppendLine("{");
            }

            var typeHeader = node.IsGenericOverRunner
                ? $"    partial class {node.TypeName}<TRunner>"
                : $"    partial class {node.TypeName}";
            sb.AppendLine(typeHeader);
            sb.AppendLine("    {");
            sb.AppendLine($"        public {node.TypeName}()");
            sb.AppendLine("        {");

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            {p.FieldName} = new InputPort<{p.CSharpType}>();");
            }

            if (node.HasInitializePortsHook || node.Outputs.Length > 0)
            {
                sb.AppendLine("            InitializePorts();");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            Ports.Add(\"{p.FieldName}\", {p.FieldName});");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"            Ports.Add(\"{p.FieldName}\", {p.FieldName});");
            }

            sb.AppendLine("        }");

            if (node.Outputs.Length > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        partial void InitializePorts();");
            }

            sb.AppendLine("    }");
            if (!string.IsNullOrEmpty(node.TypeNamespace))
            {
                sb.AppendLine("}");
            }

            spc.AddSource($"{node.TypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static void EmitEditorMirror(SourceProductionContext spc, Compilation compilation, GenericNodeModel node)
        {
            var editorNs = GraphCompilationNames.EditorGraphToolkitNamespace(compilation);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Unity.GraphToolkit.Editor;");
            sb.AppendLine();
            sb.AppendLine($"namespace {editorNs}");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {node.TypeName}EditorNode : Node");
            sb.AppendLine("    {");
            if (node.IsFlowNode)
            {
                sb.AppendLine("        public const string FlowInPortName = \"FlowIn\";");
            }

            foreach (var p in node.FlowOuts)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            sb.AppendLine();
            sb.AppendLine("        protected override void OnDefinePorts(IPortDefinitionContext context)");
            sb.AppendLine("        {");
            if (node.IsFlowNode)
            {
                sb.AppendLine("            context.AddInputPort(FlowInPortName)");
                sb.AppendLine("                .WithDisplayName(string.Empty)");
                sb.AppendLine("                .WithConnectorUI(PortConnectorUI.Arrowhead)");
                sb.AppendLine("                .Build();");
            }

            foreach (var p in node.FlowOuts)
            {
                sb.AppendLine($"            context.AddOutputPort({p.FieldName}PortName)");
                sb.AppendLine($"                .WithDisplayName(\"{p.FieldName}\")");
                sb.AppendLine("                .WithConnectorUI(PortConnectorUI.Arrowhead)");
                sb.AppendLine("                .Build();");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            context.AddInputPort<{p.CSharpType}>({p.FieldName}PortName).Build();");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"            context.AddOutputPort<{p.CSharpType}>({p.FieldName}PortName).Build();");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{node.TypeName}EditorNode.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static string BuildRegistrationBlock(GraphPackageModel package, Compilation compilation, GenericNodeModel node)
        {
            var runnerFq = GraphRegistryEmitter.TrimGlobal(package.RunnerFullyQualified);
            var editorTypeFq = GraphCompilationNames.EditorGraphToolkitNamespace(compilation) + "." + node.TypeName + "EditorNode";
            var runtimeTypeFq = ClosedRuntimeTypeFq(package, node);

            var dataInputs = ToInputTriples(node.Inputs);
            var dataOutputs = ToOutputNames(node.Outputs);

            if (!node.IsFlowNode)
            {
                return GraphRegistryEmitter.BuildDataNodeRegistrationBlock(runnerFq, editorTypeFq, runtimeTypeFq, dataInputs, dataOutputs);
            }

            var flowOutNames = new List<string>();
            foreach (var p in node.FlowOuts)
            {
                flowOutNames.Add(p.FieldName);
            }

            return GraphRegistryEmitter.BuildFlowNodeRegistrationBlock(runnerFq, editorTypeFq, runtimeTypeFq, flowOutNames, dataInputs, dataOutputs);
        }

        static string ClosedRuntimeTypeFq(GraphPackageModel package, GenericNodeModel node)
        {
            var fqNoGeneric = node.FullyQualifiedNoGeneric;
            return node.IsGenericOverRunner
                ? fqNoGeneric + "<" + GraphRegistryEmitter.TrimGlobal(package.RunnerFullyQualified) + ">"
                : fqNoGeneric;
        }

        static List<(string Name, string CSharpType)> ToInputTriples(ImmutableArray<GenericNodeInputField> inputs)
        {
            var list = new List<(string, string)>();
            foreach (var p in inputs)
            {
                list.Add((p.FieldName, p.CSharpType));
            }

            return list;
        }

        static List<string> ToOutputNames(ImmutableArray<GenericNodeOutputField> outputs)
        {
            var list = new List<string>();
            foreach (var p in outputs)
            {
                list.Add(p.FieldName);
            }

            return list;
        }
    }
}
