using System.Threading;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    internal static class GraphPackageTrioEmitter
    {
        internal static void Emit(SourceProductionContext spc, Compilation compilation, ImmutableArray<GraphPackageModel> packages, CancellationToken cancellationToken)
        {
            if (packages.IsDefaultOrEmpty)
            {
                return;
            }

            var editorAsm = IsEditorAssembly(compilation);
            foreach (var p in packages)
            {
                DispatchOnePackage(spc, compilation, editorAsm, p, cancellationToken);
            }
        }

        static void DispatchOnePackage(SourceProductionContext spc, Compilation compilation, bool editorAsm, GraphPackageModel p, CancellationToken cancellationToken)
        {
            // The GraphAsset SO is intentionally NOT emitted — it must be hand-written by the consumer.
            // Unity's MonoScript binding (used by AssetImportContext.AddObjectToAsset) only resolves ScriptableObject types
            // declared in a real .cs file with matching name; generator-emitted virtual files do not satisfy that lookup.
            if (editorAsm)
            {
                AddEditorSources(spc, compilation, p);
            }

            GraphPayloadNodeEmitter.Emit(spc, compilation, editorAsm, p, cancellationToken);
        }

        static bool IsEditorAssembly(Compilation compilation)
        {
            var name = compilation.Assembly.Name;
            return name != null && name.EndsWith(".Editor", System.StringComparison.Ordinal);
        }

        static void AddEditorSources(SourceProductionContext spc, Compilation compilation, GraphPackageModel p)
        {
            var graphSb = new StringBuilder();
            AppendEditorGraphFile(graphSb, compilation, p);
            var graphPath = $"{p.GraphStem}Graph.g.cs";
            var graphText = graphSb.ToString();
            var graphSource = SourceText.From(graphText, Encoding.UTF8);
            spc.AddSource(graphPath, graphSource);
            var impSb = new StringBuilder();
            AppendEditorImporterFile(impSb, compilation, p);
            var impPath = $"{p.GraphStem}GraphImporter.g.cs";
            var impText = impSb.ToString();
            var impSource = SourceText.From(impText, Encoding.UTF8);
            spc.AddSource(impPath, impSource);
        }

        static string EditorGraphToolkitNamespace(Compilation compilation)
        {
            return EditorPackageRoot(compilation) + ".Editor.GToolkit";
        }

        static string EditorImporterNamespace(Compilation compilation)
        {
            return EditorPackageRoot(compilation) + ".Editor";
        }

        static string EditorPackageRoot(Compilation compilation)
        {
            var name = compilation.Assembly.Name ?? "";
            const string suffix = ".Editor";
            if (name.EndsWith(suffix, System.StringComparison.Ordinal))
            {
                return name.Substring(0, name.Length - suffix.Length);
            }

            return name;
        }

        static void AppendEditorGraphFile(StringBuilder sb, Compilation compilation, GraphPackageModel p)
        {
            AppendEditorGraphHeader(sb, compilation, p);
            sb.AppendLine();
            sb.AppendLine($"namespace {EditorGraphToolkitNamespace(compilation)}");
            sb.AppendLine("{");
            AppendEditorGraphBody(sb, p);
            sb.AppendLine("}");
        }

        static void AppendEditorGraphHeader(StringBuilder sb, Compilation compilation, GraphPackageModel p)
        {
            var pkgRoot = EditorPackageRoot(compilation);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine($"using {pkgRoot};");
            AppendRunnerUsingIfNeeded(sb, p);
            sb.AppendLine("using Unity.GraphToolkit.Editor;");
            sb.AppendLine("using UnityEditor;");
        }

        static void AppendRunnerUsingIfNeeded(StringBuilder sb, GraphPackageModel p)
        {
            if (string.IsNullOrEmpty(p.RunnerNamespace))
            {
                return;
            }

            sb.AppendLine($"using {p.RunnerNamespace};");
        }

        static void AppendEditorGraphBody(StringBuilder sb, GraphPackageModel p)
        {
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [Graph(AssetExtension)]");
            sb.AppendLine($"    public sealed class {p.GraphStem}Graph : Graph<{p.RunnerTypeName}>");
            sb.AppendLine("    {");
            AppendEditorGraphConstantsAndMenu(sb, p);
            sb.AppendLine("    }");
        }

        static void AppendEditorGraphConstantsAndMenu(StringBuilder sb, GraphPackageModel p)
        {
            var extLit = EscapeString(p.Extension);
            var promptLit = EscapeString(CreatePromptTitle(p.AssetMenu));
            var menuLit = EscapeString(MenuItemPath(p.AssetMenu));
            sb.AppendLine($"        internal const string AssetExtension = \"{extLit}\";");
            sb.AppendLine($"        const string k_CreateMenuName = \"{promptLit}\";");
            sb.AppendLine($"        [MenuItem(\"{menuLit}\")]");
            sb.AppendLine($"        static void CreateAssetFile() =>");
            sb.AppendLine($"            GraphDatabase.PromptInProjectBrowserToCreateNewAsset<{p.GraphStem}Graph>(k_CreateMenuName);");
        }

        static string MenuItemPath(string assetMenu)
        {
            return "Assets/Create/" + assetMenu;
        }

        static string CreatePromptTitle(string assetMenu)
        {
            return assetMenu.Replace("/", " ");
        }

        static string EscapeString(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        static void AppendEditorImporterFile(StringBuilder sb, Compilation compilation, GraphPackageModel p)
        {
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"using {EditorGraphToolkitNamespace(compilation)};");
            AppendRunnerUsingIfNeeded(sb, p);
            sb.AppendLine("using UnityEditor.AssetImporters;");
            sb.AppendLine();
            sb.AppendLine($"namespace {EditorImporterNamespace(compilation)}");
            sb.AppendLine("{");
            AppendImporterBody(sb, p);
            sb.AppendLine("}");
        }

        static void AppendImporterBody(StringBuilder sb, GraphPackageModel p)
        {
            sb.AppendLine($"    [ScriptedImporter(1, {p.GraphStem}Graph.AssetExtension)]");
            sb.AppendLine($"    public sealed class {p.GraphStem}GraphImporter : GraphAssetImporterBase<{p.GraphStem}Graph, {p.RunnerTypeName}, {p.GraphStem}GraphAsset>");
            sb.AppendLine("    {");
            sb.AppendLine("        protected override GraphBakeResult Bake(");
            sb.AppendLine($"            {p.GraphStem}Graph graph, {p.GraphStem}GraphAsset? previousRuntime) =>");
            sb.AppendLine("            GraphBaker.Bake(graph, previousRuntime);");
            sb.AppendLine("    }");
        }
    }
}
