using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Builds the per-package registry partial and the per-payload registration snippets the baker
    /// reads to dispatch editor nodes → runtime nodes generically.
    /// <para>Post-M3 phase 2 (decision #4): port IDs are strings (field names). Registrations are
    /// HashSets of valid port names per role; the name is the id end-to-end.</para>
    /// </summary>
    internal static class GraphRegistryEmitter
    {
        internal const string EditorRegistryNamespace = "Scaffold.GraphFlow.Editor";
        internal const string PackageEditorGToolkitNamespace = "Scaffold.GraphFlow.Editor.GToolkit";
        internal const string PackageRuntimeNamespace = "Scaffold.GraphFlow";
        internal const string EditorRegistryTypeName = "GraphPackageRegistry";

        internal static string ResolveRegistryNamespace(GraphPackageModel package, Compilation compilation)
        {
            if (!string.IsNullOrEmpty(package.RegistryNamespace))
            {
                return package.RegistryNamespace;
            }

            return GraphCompilationNames.EditorPackageRoot(compilation) + ".Editor.Generated";
        }

        internal static string RegistryTypeName(GraphPackageModel package)
        {
            return package.GraphStem + "GraphRegistry";
        }

        internal static void EmitRegistryFile(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            IReadOnlyList<string> registrationBlocks)
        {
            var ns = ResolveRegistryNamespace(package, compilation);
            var typeName = RegistryTypeName(package);
            var runnerFq = GraphCompilationNames.TrimGlobal(package.RunnerFullyQualified);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"using {EditorRegistryNamespace};");
            sb.AppendLine($"using {PackageRuntimeNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static partial class {typeName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {EditorRegistryTypeName}<{runnerFq}> Instance = Build();");
            sb.AppendLine();
            sb.AppendLine($"        static {EditorRegistryTypeName}<{runnerFq}> Build()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {EditorRegistryTypeName}<{runnerFq}>();");
            sb.AppendLine("            RegisterGenerated(r);");
            sb.AppendLine("            RegisterOnTrigger(r);");
            sb.AppendLine("            RegisterReturn(r);");
            sb.AppendLine("            RegisterAdditional(r);");
            sb.AppendLine("            return r;");
            sb.AppendLine("        }");
            sb.AppendLine();
            AppendOnTriggerRegistration(sb, package, compilation, runnerFq);
            AppendReturnRegistration(sb, package, compilation, runnerFq);
            sb.AppendLine($"        static partial void RegisterAdditional({EditorRegistryTypeName}<{runnerFq}> r);");
            sb.AppendLine();
            sb.AppendLine($"        static void RegisterGenerated({EditorRegistryTypeName}<{runnerFq}> r)");
            sb.AppendLine("        {");
            foreach (var block in registrationBlocks)
            {
                sb.Append(block);
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static void AppendOnTriggerRegistration(StringBuilder sb, GraphPackageModel package, Compilation compilation, string runnerFq)
        {
            // The shim is emitted into the same namespace as the registry partial; both live in the
            // package's editor asm. The catalog is in the runtime asm under
            // <see cref="GraphCatalogEmitter.ResolveCatalogNamespace"/>; the registry pulls from it
            // via a fully-qualified reference so the using list stays minimal.
            var shimNs    = ResolveRegistryNamespace(package, compilation);
            var shimFq    = shimNs + ".OnTriggerEditorNode";
            var catalogNs = GraphCatalogEmitter.ResolveCatalogNamespace(package, compilation);
            var catalogFq = catalogNs + "." + package.GraphStem + GraphCatalogEmitter.CatalogClassSuffix;

            sb.AppendLine($"        static void RegisterOnTrigger({EditorRegistryTypeName}<{runnerFq}> r)");
            sb.AppendLine("        {");
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({shimFq}),");
            sb.AppendLine("                Factory = node =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var typed = ({shimFq})node;");
            sb.AppendLine($"                    var eventOpt = typed.GetNodeOptionByName(global::Scaffold.GraphFlow.Editor.Nodes.OnTriggerEditorNode<{catalogFq}.EventType>.EventTypeOptionName);");
            sb.AppendLine($"                    if (eventOpt == null || !eventOpt.TryGetValue<{catalogFq}.EventType>(out var picked) || picked == {catalogFq}.EventType.None)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        throw new System.InvalidOperationException(\"OnTrigger node has no EventType selected.\");");
            sb.AppendLine("                    }");
            sb.AppendLine($"                    var entry = {catalogFq}.Resolve(picked);");
            sb.AppendLine("                    if (entry?.CreateRuntime == null)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        throw new System.InvalidOperationException($\"OnTrigger catalog entry for '{picked}' is missing a runtime factory.\");");
            sb.AppendLine("                    }");
            sb.AppendLine("                    var rt = entry.CreateRuntime();");
            sb.AppendLine($"                    var timingOpt = typed.GetNodeOptionByName(global::Scaffold.GraphFlow.Editor.Nodes.OnTriggerEditorNode<{catalogFq}.EventType>.TimingOptionName);");
            sb.AppendLine("                    if (timingOpt != null && timingOpt.TryGetValue<global::Scaffold.GraphFlow.Timing>(out var pickedTiming) && rt is global::Scaffold.GraphFlow.IOnTrigger trig)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        trig.Timing = pickedTiming;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return rt;");
            sb.AppendLine("                },");
            sb.AppendLine($"                FlowOutputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal) {{ global::Scaffold.GraphFlow.Editor.Nodes.OnTriggerEditorNode<{catalogFq}.EventType>.FlowOutPortName }},");
            // OnTrigger's per-event-field ports are dynamic (added at edit time once the user picks
            // an EventType). The static registration enumerates the *union* of every event's field
            // names so the EFG-V03 edge-pairing validator can recognize them. The editor only
            // surfaces names that actually exist on the picked event, so the union is safe.
            sb.AppendLine($"                DataOutputPortNames = new System.Collections.Generic.HashSet<string>({catalogFq}.AllEventDataOutputPortNames, System.StringComparer.Ordinal),");
            sb.AppendLine($"                DataInputPortNames  = new System.Collections.Generic.HashSet<string>({catalogFq}.AllEventDataInputPortNames,  System.StringComparer.Ordinal),");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        static void AppendReturnRegistration(StringBuilder sb, GraphPackageModel package, Compilation compilation, string runnerFq)
        {
            var shimNs    = ResolveRegistryNamespace(package, compilation);
            var shimFq    = shimNs + ".ReturnEditorNode";
            var catalogNs = GraphCatalogEmitter.ResolveCatalogNamespace(package, compilation);
            var catalogFq = catalogNs + "." + package.GraphStem + GraphCatalogEmitter.CatalogClassSuffix;
            var baseFq    = $"global::Scaffold.GraphFlow.Editor.Nodes.ReturnEditorNode<{catalogFq}.ReturnType>";

            sb.AppendLine($"        static void RegisterReturn({EditorRegistryTypeName}<{runnerFq}> r)");
            sb.AppendLine("        {");
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({shimFq}),");
            sb.AppendLine("                Factory = node =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var typed = ({shimFq})node;");
            sb.AppendLine($"                    var opt = typed.GetNodeOptionByName({baseFq}.ResultTypeOptionName);");
            sb.AppendLine($"                    if (opt == null || !opt.TryGetValue<{catalogFq}.ReturnType>(out var picked) || picked == {catalogFq}.ReturnType.None)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        // No ResultType picked — fall back to the void Return (equivalent to `return;`).");
            sb.AppendLine("                        return new global::Scaffold.GraphFlow.Nodes.Return();");
            sb.AppendLine("                    }");
            sb.AppendLine($"                    var entry = {catalogFq}.Resolve(picked);");
            sb.AppendLine("                    if (entry?.CreateRuntime == null)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        throw new System.InvalidOperationException($\"Return catalog entry for '{picked}' is missing a runtime factory.\");");
            sb.AppendLine("                    }");
            sb.AppendLine("                    return entry.CreateRuntime();");
            sb.AppendLine("                },");
            sb.AppendLine($"                FlowInputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal) {{ {baseFq}.FlowInPortName }},");
            sb.AppendLine($"                DataInputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal) {{ {baseFq}.ValuePortName }},");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        internal static string BuildEntryRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string payloadTypeFq,
            string flowOutPortName,
            IReadOnlyList<string> dataOutputs,
            IReadOnlyList<string>? extraFlowOutputs = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            sb.AppendLine("                FlowOutputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    \"{flowOutPortName}\",");
            if (extraFlowOutputs != null)
            {
                foreach (var name in extraFlowOutputs)
                {
                    sb.AppendLine($"                    \"{name}\",");
                }
            }

            sb.AppendLine("                },");
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine($"                EntryTypeId = typeof({payloadTypeFq}).AssemblyQualifiedName,");
            sb.AppendLine("            });");
            return sb.ToString();
        }

        internal static string BuildExecutableActionRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string flowInPortName,
            IReadOnlyList<(string Name, string CSharpType)> dataInputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            AppendInlineFactory(sb, editorTypeFq, runtimeTypeFq, dataInputs);
            sb.AppendLine("                FlowInputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    \"{flowInPortName}\",");
            sb.AppendLine("                },");
            AppendDataInputs(sb, dataInputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        internal static string BuildCommandRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string flowInPortName,
            string flowOutPortName,
            IReadOnlyList<(string Name, string CSharpType)> dataInputs,
            IReadOnlyList<string> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            AppendInlineFactory(sb, editorTypeFq, runtimeTypeFq, dataInputs);
            sb.AppendLine("                FlowInputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    \"{flowInPortName}\",");
            sb.AppendLine("                },");
            sb.AppendLine("                FlowOutputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    \"{flowOutPortName}\",");
            sb.AppendLine("                },");
            AppendDataInputs(sb, dataInputs);
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        /// <summary>
        /// Build a registration block for a pure-data <c>[GraphNode]</c> or hand-written data node
        /// (no flow ports, no entry-type id).
        /// </summary>
        internal static string BuildDataNodeRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            IReadOnlyList<(string Name, string CSharpType)> dataInputs,
            IReadOnlyList<string> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            AppendDataInputs(sb, dataInputs);
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        /// <summary>
        /// Build a registration block for a <c>[GraphNode]</c> flow node with explicit flow-in plus
        /// N flow-outs and arbitrary data ports.
        /// </summary>
        internal static string BuildFlowNodeRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            bool hasFlowIn,
            IReadOnlyList<string> flowOutputs,
            IReadOnlyList<(string Name, string CSharpType)> dataInputs,
            IReadOnlyList<string> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            if (hasFlowIn)
            {
                sb.AppendLine("                FlowInputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    \"FlowIn\",");
                sb.AppendLine("                },");
            }

            if (flowOutputs.Count > 0)
            {
                sb.AppendLine("                FlowOutputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
                sb.AppendLine("                {");
                foreach (var name in flowOutputs)
                {
                    sb.AppendLine($"                    \"{name}\",");
                }

                sb.AppendLine("                },");
            }

            AppendDataInputs(sb, dataInputs);
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        static void AppendInlineFactory(
            StringBuilder sb,
            string editorTypeFq,
            string runtimeTypeFq,
            IReadOnlyList<(string Name, string CSharpType)> dataInputs)
        {
            if (dataInputs.Count == 0)
            {
                sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
                return;
            }

            sb.AppendLine("                Factory = node =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var rt = new {runtimeTypeFq}();");
            sb.AppendLine($"                    var typed = ({editorTypeFq})node;");
            foreach (var f in dataInputs)
            {
                sb.AppendLine($"                    {{");
                sb.AppendLine($"                        var p = typed.GetInputPortByName(\"{f.Name}\");");
                sb.AppendLine($"                        if (p != null && {EditorRegistryNamespace}.PortValueResolver.TryResolve<{f.CSharpType}>(p, out var v))");
                sb.AppendLine($"                            rt.{f.Name} = v{NullableCoalesce(f.CSharpType)};");
                sb.AppendLine($"                    }}");
            }

            sb.AppendLine("                    return rt;");
            sb.AppendLine("                },");
        }

        static string NullableCoalesce(string csharpType)
        {
            return csharpType == "string" ? " ?? \"\"" : "";
        }

        static void AppendDataInputs(StringBuilder sb, IReadOnlyList<(string Name, string CSharpType)> dataInputs)
        {
            if (dataInputs.Count == 0)
            {
                return;
            }

            sb.AppendLine("                DataInputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var f in dataInputs)
            {
                sb.AppendLine($"                    \"{f.Name}\",");
            }

            sb.AppendLine("                },");
        }

        static void AppendDataOutputs(StringBuilder sb, IReadOnlyList<string> dataOutputs)
        {
            if (dataOutputs.Count == 0)
            {
                return;
            }

            sb.AppendLine("                DataOutputPortNames = new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var name in dataOutputs)
            {
                sb.AppendLine($"                    \"{name}\",");
            }

            sb.AppendLine("                },");
        }

    }
}
