using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Builds the per-package registry partial and the per-payload registration snippets the baker
    /// reads to dispatch editor nodes → runtime nodes generically.
    /// <para>Port-id lookup dicts in the registry use literal int values (rather than referencing a
    /// runtime <c>Ports</c> static class that no longer exists). Same id-derivation pipeline drives
    /// both the runtime ctor's <c>Ports.Add(id, port)</c> call and the registry's
    /// <c>["Name"] = id</c> entries.</para>
    /// </summary>
    internal static class GraphRegistryEmitter
    {
        internal const string EditorRegistryNamespace = "Scaffold.GraphFlow.Editor";
        internal const string PackageEditorGToolkitNamespace = "Scaffold.GraphFlow.Editor.GToolkit";
        internal const string PackageRuntimeNamespace = "Scaffold.GraphFlow";
        internal const string EditorRegistryTypeName = "GraphPackageRegistry";

        internal static string ResolveRegistryNamespace(GraphPackageModel package, Compilation compilation)
        {
            if (!string.IsNullOrEmpty(package.RegistryNamespace))
            {
                return package.RegistryNamespace;
            }

            return GraphCompilationNames.EditorPackageRoot(compilation) + ".Editor.Generated";
        }

        internal static string RegistryTypeName(GraphPackageModel package)
        {
            return package.GraphStem + "GraphRegistry";
        }

        internal static void EmitRegistryFile(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            IReadOnlyList<string> registrationBlocks)
        {
            var ns = ResolveRegistryNamespace(package, compilation);
            var typeName = RegistryTypeName(package);
            var runnerFq = TrimGlobal(package.RunnerFullyQualified);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"using {EditorRegistryNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static partial class {typeName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {EditorRegistryTypeName}<{runnerFq}> Instance = Build();");
            sb.AppendLine();
            sb.AppendLine($"        static {EditorRegistryTypeName}<{runnerFq}> Build()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {EditorRegistryTypeName}<{runnerFq}>();");
            sb.AppendLine("            RegisterGenerated(r);");
            sb.AppendLine("            RegisterAdditional(r);");
            sb.AppendLine("            return r;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        static partial void RegisterAdditional({EditorRegistryTypeName}<{runnerFq}> r);");
            sb.AppendLine();
            sb.AppendLine($"        static void RegisterGenerated({EditorRegistryTypeName}<{runnerFq}> r)");
            sb.AppendLine("        {");
            foreach (var block in registrationBlocks)
            {
                sb.Append(block);
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        internal static string BuildEntryRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string payloadTypeFq,
            string flowOutPortName,
            int flowOutPortId,
            IReadOnlyList<(string Name, int Id)> dataOutputs,
            IReadOnlyList<(string Name, int Id)>? extraFlowOutputs = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            sb.AppendLine("                FlowOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowOutPortName}\"] = {PortIdLiteral(flowOutPortId)},");
            if (extraFlowOutputs != null)
            {
                foreach (var (name, id) in extraFlowOutputs)
                {
                    sb.AppendLine($"                    [\"{name}\"] = {PortIdLiteral(id)},");
                }
            }

            sb.AppendLine("                },");
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine($"                EntryTypeId = typeof({payloadTypeFq}).AssemblyQualifiedName,");
            sb.AppendLine("            });");
            return sb.ToString();
        }

        internal static string BuildExecutableActionRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string flowInPortName,
            int flowInPortId,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            AppendInlineFactory(sb, editorTypeFq, runtimeTypeFq, dataInputs);
            sb.AppendLine("                FlowInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowInPortName}\"] = {PortIdLiteral(flowInPortId)},");
            sb.AppendLine("                },");
            AppendDataInputs(sb, dataInputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        internal static string BuildCommandRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string flowInPortName,
            int flowInPortId,
            string flowOutPortName,
            int flowOutPortId,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs,
            IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            AppendInlineFactory(sb, editorTypeFq, runtimeTypeFq, dataInputs);
            sb.AppendLine("                FlowInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowInPortName}\"] = {PortIdLiteral(flowInPortId)},");
            sb.AppendLine("                },");
            sb.AppendLine("                FlowOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowOutPortName}\"] = {PortIdLiteral(flowOutPortId)},");
            sb.AppendLine("                },");
            AppendDataInputs(sb, dataInputs);
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        /// <summary>
        /// Build a registration block for a pure-data <c>[GraphNode]</c> or hand-written data node
        /// (no flow ports, no entry-type id). Used by the generic-node emitter and any
        /// <c>RegisterAdditional</c> hand-rolled equivalents.
        /// </summary>
        internal static string BuildDataNodeRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs,
            IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            AppendDataInputs(sb, dataInputs);
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        /// <summary>
        /// Build a registration block for a <c>[GraphNode]</c> flow node (RuntimeNode&lt;TRunner&gt; with
        /// an explicit flow-in plus N flow-outs and arbitrary data ports).
        /// </summary>
        internal static string BuildFlowNodeRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            int flowInPortId,
            IReadOnlyList<(string Name, int Id)> flowOutputs,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs,
            IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            sb.AppendLine("                FlowInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"FlowIn\"] = {PortIdLiteral(flowInPortId)},");
            sb.AppendLine("                },");
            if (flowOutputs.Count > 0)
            {
                sb.AppendLine("                FlowOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
                sb.AppendLine("                {");
                foreach (var p in flowOutputs)
                {
                    sb.AppendLine($"                    [\"{p.Name}\"] = {PortIdLiteral(p.Id)},");
                }

                sb.AppendLine("                },");
            }

            AppendDataInputs(sb, dataInputs);
            AppendDataOutputs(sb, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        static void AppendInlineFactory(
            StringBuilder sb,
            string editorTypeFq,
            string runtimeTypeFq,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs)
        {
            if (dataInputs.Count == 0)
            {
                sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
                return;
            }

            sb.AppendLine("                Factory = node =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var rt = new {runtimeTypeFq}();");
            sb.AppendLine($"                    var typed = ({editorTypeFq})node;");
            foreach (var f in dataInputs)
            {
                sb.AppendLine($"                    {{");
                sb.AppendLine($"                        var p = typed.GetInputPortByName({editorTypeFq}.{f.Name}PortName);");
                sb.AppendLine($"                        if (p != null && !p.isConnected && p.TryGetValue<{f.CSharpType}>(out var v))");
                sb.AppendLine($"                            rt.{f.Name} = v{NullableCoalesce(f.CSharpType)};");
                sb.AppendLine($"                    }}");
            }

            sb.AppendLine("                    return rt;");
            sb.AppendLine("                },");
        }

        static string NullableCoalesce(string csharpType)
        {
            // Only string needs the !-coalesce since TryGetValue<string> can hand back a null.
            return csharpType == "string" ? " ?? \"\"" : "";
        }

        static void AppendDataInputs(StringBuilder sb, IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs)
        {
            if (dataInputs.Count == 0)
            {
                return;
            }

            sb.AppendLine("                DataInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var f in dataInputs)
            {
                sb.AppendLine($"                    [\"{f.Name}\"] = {PortIdLiteral(f.Id)},");
            }

            sb.AppendLine("                },");
        }

        static void AppendDataOutputs(StringBuilder sb, IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            if (dataOutputs.Count == 0)
            {
                return;
            }

            sb.AppendLine("                DataOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var f in dataOutputs)
            {
                sb.AppendLine($"                    [\"{f.Name}\"] = {PortIdLiteral(f.Id)},");
            }

            sb.AppendLine("                },");
        }

        internal static string PortIdLiteral(int pid) => "unchecked((int)0x" + ((uint)pid).ToString("X8") + "u)";

        internal static string TrimGlobal(string fq)
        {
            return fq.StartsWith("global::", System.StringComparison.Ordinal) ? fq.Substring(8) : fq;
        }
    }
}
