using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Builds the per-package registry partial and the per-payload registration snippets
    /// the baker reads to dispatch editor nodes → runtime nodes generically.
    /// </summary>
    internal static class GraphRegistryEmitter
    {
        internal const string EditorRegistryNamespace = "Scaffold.GraphFlow.M0.Editor";
        internal const string EditorRegistryTypeName = "GraphPackageRegistry";

        internal static string ResolveRegistryNamespace(GraphPackageModel package, Compilation compilation)
        {
            if (!string.IsNullOrEmpty(package.RegistryNamespace))
            {
                return package.RegistryNamespace;
            }

            return GraphCompilationNames.EditorPackageRoot(compilation) + ".Editor.Generated";
        }

        internal static string RegistryTypeName(GraphPackageModel package)
        {
            return package.GraphStem + "GraphRegistry";
        }

        internal static void EmitRegistryFile(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            IReadOnlyList<string> registrationBlocks)
        {
            var ns = ResolveRegistryNamespace(package, compilation);
            var typeName = RegistryTypeName(package);
            var runnerFq = TrimGlobal(package.RunnerFullyQualified);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"using {EditorRegistryNamespace};");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static partial class {typeName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {EditorRegistryTypeName}<{runnerFq}> Instance = Build();");
            sb.AppendLine();
            sb.AppendLine($"        static {EditorRegistryTypeName}<{runnerFq}> Build()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var r = new {EditorRegistryTypeName}<{runnerFq}>();");
            sb.AppendLine("            RegisterGenerated(r);");
            sb.AppendLine("            RegisterAdditional(r);");
            sb.AppendLine("            return r;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        static partial void RegisterAdditional({EditorRegistryTypeName}<{runnerFq}> r);");
            sb.AppendLine();
            sb.AppendLine($"        static void RegisterGenerated({EditorRegistryTypeName}<{runnerFq}> r)");
            sb.AppendLine("        {");
            foreach (var block in registrationBlocks)
            {
                sb.Append(block);
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{typeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        internal static string BuildEntryRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string payloadTypeFq,
            string flowOutPortName,
            IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            sb.AppendLine("                FlowOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowOutPortName}\"] = {runtimeTypeFq}.Ports.FlowOut,");
            sb.AppendLine("                },");
            AppendDataOutputs(sb, runtimeTypeFq, dataOutputs);
            sb.AppendLine($"                EntryTypeId = typeof({payloadTypeFq}).AssemblyQualifiedName,");
            sb.AppendLine("            });");
            return sb.ToString();
        }

        internal static string BuildExecutableActionRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string flowInPortName,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            AppendInlineFactory(sb, editorTypeFq, runtimeTypeFq, dataInputs);
            sb.AppendLine("                FlowInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowInPortName}\"] = {runtimeTypeFq}.Ports.FlowIn,");
            sb.AppendLine("                },");
            AppendDataInputs(sb, runtimeTypeFq, dataInputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        internal static string BuildCommandRegistrationBlock(
            string runnerFq,
            string editorTypeFq,
            string runtimeTypeFq,
            string flowInPortName,
            string flowOutPortName,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs,
            IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            AppendInlineFactory(sb, editorTypeFq, runtimeTypeFq, dataInputs);
            sb.AppendLine("                FlowInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowInPortName}\"] = {runtimeTypeFq}.Ports.FlowIn,");
            sb.AppendLine("                },");
            sb.AppendLine("                FlowOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    [\"{flowOutPortName}\"] = {runtimeTypeFq}.Ports.FlowOut,");
            sb.AppendLine("                },");
            AppendDataInputs(sb, runtimeTypeFq, dataInputs);
            AppendDataOutputs(sb, runtimeTypeFq, dataOutputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        static void AppendInlineFactory(
            StringBuilder sb,
            string editorTypeFq,
            string runtimeTypeFq,
            IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs)
        {
            if (dataInputs.Count == 0)
            {
                sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
                return;
            }

            sb.AppendLine("                Factory = node =>");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var rt = new {runtimeTypeFq}();");
            sb.AppendLine($"                    var typed = ({editorTypeFq})node;");
            foreach (var f in dataInputs)
            {
                sb.AppendLine($"                    {{");
                sb.AppendLine($"                        var p = typed.GetInputPortByName({editorTypeFq}.{f.Name}PortName);");
                sb.AppendLine($"                        if (p != null && !p.isConnected && p.TryGetValue<{f.CSharpType}>(out var v))");
                sb.AppendLine($"                            rt.{f.Name} = v{NullableCoalesce(f.CSharpType)};");
                sb.AppendLine($"                    }}");
            }

            sb.AppendLine("                    return rt;");
            sb.AppendLine("                },");
        }

        static string NullableCoalesce(string csharpType)
        {
            // Only string needs the !-coalesce since TryGetValue<string> can hand back a null.
            return csharpType == "string" ? " ?? \"\"" : "";
        }

        static void AppendDataInputs(StringBuilder sb, string runtimeTypeFq, IReadOnlyList<(string Name, int Id, string CSharpType)> dataInputs)
        {
            if (dataInputs.Count == 0)
            {
                return;
            }

            sb.AppendLine("                DataInputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var f in dataInputs)
            {
                sb.AppendLine($"                    [\"{f.Name}\"] = {runtimeTypeFq}.Ports.{f.Name},");
            }

            sb.AppendLine("                },");
        }

        static void AppendDataOutputs(StringBuilder sb, string runtimeTypeFq, IReadOnlyList<(string Name, int Id)> dataOutputs)
        {
            if (dataOutputs.Count == 0)
            {
                return;
            }

            sb.AppendLine("                DataOutputPortIds = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var f in dataOutputs)
            {
                sb.AppendLine($"                    [\"{f.Name}\"] = {runtimeTypeFq}.Ports.{f.Name},");
            }

            sb.AppendLine("                },");
        }

        internal static string TrimGlobal(string fq)
        {
            return fq.StartsWith("global::", System.StringComparison.Ordinal) ? fq.Substring(8) : fq;
        }
    }
}
