using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Scaffold.GraphFlow.PackageGenerator
{
    /// <summary>
    /// Emits the editor-side mirror + per-package registry entry for hand-written <c>[GraphNode]</c> RuntimeNodes.
    /// Runtime class is hand-written by the consumer; only the editor + registry are generated.
    /// Reuses <see cref="GraphRegistryEmitter"/>'s registry composition; the editor mirror follows the same port-emit conventions as <see cref="GraphPayloadNodeEmitter"/>.
    /// </summary>
    internal static class GraphGenericNodeEmitter
    {
        internal static void EmitEditorAndRegistrations(
            SourceProductionContext spc,
            Compilation compilation,
            GraphPackageModel package,
            ImmutableArray<GenericNodeModel> nodes,
            List<string> registrationBlocks)
        {
            if (nodes.IsDefaultOrEmpty)
            {
                return;
            }

            var editorNs = GraphCompilationNames.EditorGraphToolkitNamespace(compilation);
            foreach (var node in nodes)
            {
                EmitEditorMirror(spc, editorNs, node);
                registrationBlocks.Add(BuildRegistrationBlock(package, editorNs, node));
            }
        }

        static void EmitEditorMirror(SourceProductionContext spc, string editorNs, GenericNodeModel node)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Unity.GraphToolkit.Editor;");
            sb.AppendLine();
            sb.AppendLine($"namespace {editorNs}");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public sealed class {node.TypeName}EditorNode : Node");
            sb.AppendLine("    {");
            AppendPortNameConstants(sb, node);
            sb.AppendLine();
            sb.AppendLine("        protected override void OnDefinePorts(IPortDefinitionContext context)");
            sb.AppendLine("        {");
            AppendPortDefinitions(sb, node);
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{node.TypeName}EditorNode.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        static void AppendPortNameConstants(StringBuilder sb, GenericNodeModel node)
        {
            foreach (var p in node.FlowIns)
            {
                sb.AppendLine($"        public const string {p.Name}PortName = \"{p.Name}\";");
            }

            foreach (var p in node.FlowOuts)
            {
                sb.AppendLine($"        public const string {p.Name}PortName = \"{p.Name}\";");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"        public const string {p.FieldName}PortName = \"{p.FieldName}\";");
            }
        }

        static void AppendPortDefinitions(StringBuilder sb, GenericNodeModel node)
        {
            foreach (var p in node.FlowIns)
            {
                sb.AppendLine($"            context.AddInputPort({p.Name}PortName)");
                sb.AppendLine("                .WithDisplayName(string.Empty)");
                sb.AppendLine("                .WithConnectorUI(PortConnectorUI.Arrowhead)");
                sb.AppendLine("                .Build();");
            }

            foreach (var p in node.FlowOuts)
            {
                sb.AppendLine($"            context.AddOutputPort({p.Name}PortName)");
                sb.AppendLine($"                .WithDisplayName(\"{p.Name}\")");
                sb.AppendLine("                .WithConnectorUI(PortConnectorUI.Arrowhead)");
                sb.AppendLine("                .Build();");
            }

            foreach (var p in node.Inputs)
            {
                sb.AppendLine($"            context.AddInputPort<{p.CSharpType}>({p.FieldName}PortName).Build();");
            }

            foreach (var p in node.Outputs)
            {
                sb.AppendLine($"            context.AddOutputPort<{p.CSharpType}>({p.FieldName}PortName).Build();");
            }
        }

        static string BuildRegistrationBlock(GraphPackageModel package, string editorNs, GenericNodeModel node)
        {
            var runnerFq = GraphRegistryEmitter.TrimGlobal(package.RunnerFullyQualified);
            var editorTypeFq = editorNs + "." + node.TypeName + "EditorNode";
            var runtimeTypeFq = ClosedRuntimeTypeFq(package, node);

            var sb = new StringBuilder();
            sb.AppendLine($"            r.Register(new {GraphRegistryEmitter.EditorRegistryTypeName}<{runnerFq}>.NodeRegistration");
            sb.AppendLine("            {");
            sb.AppendLine($"                EditorNodeType = typeof({editorTypeFq}),");
            sb.AppendLine($"                Factory = _ => new {runtimeTypeFq}(),");
            AppendFlowDict(sb, "FlowInputPortIds", node.FlowIns);
            AppendFlowDict(sb, "FlowOutputPortIds", node.FlowOuts);
            AppendDataDict(sb, "DataInputPortIds", node.Inputs);
            AppendDataDict(sb, "DataOutputPortIds", node.Outputs);
            sb.AppendLine("            });");
            return sb.ToString();
        }

        static string ClosedRuntimeTypeFq(GraphPackageModel package, GenericNodeModel node)
        {
            var fqNoGeneric = node.FullyQualifiedNoGeneric;
            return node.IsGenericOverRunner
                ? fqNoGeneric + "<" + GraphRegistryEmitter.TrimGlobal(package.RunnerFullyQualified) + ">"
                : fqNoGeneric;
        }

        // Generic-node port labels and Ports-const names may diverge (e.g. label "True" vs const "TrueOut"),
        // so emit the literal port id rather than a Ports.X reference. The attribute on the runtime type is the source of truth either way.
        static string PortIdLiteral(int pid) => "unchecked((int)0x" + ((uint)pid).ToString("X8") + "u)";

        static void AppendFlowDict(StringBuilder sb, string dictName, ImmutableArray<GenericNodeFlowPort> ports)
        {
            if (ports.IsDefaultOrEmpty)
            {
                return;
            }

            sb.AppendLine($"                {dictName} = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var p in ports)
            {
                sb.AppendLine($"                    [\"{p.Name}\"] = {PortIdLiteral(p.PortId)},");
            }

            sb.AppendLine("                },");
        }

        static void AppendDataDict(StringBuilder sb, string dictName, ImmutableArray<GenericNodeDataPort> ports)
        {
            if (ports.IsDefaultOrEmpty)
            {
                return;
            }

            sb.AppendLine($"                {dictName} = new System.Collections.Generic.Dictionary<string, int>(System.StringComparer.Ordinal)");
            sb.AppendLine("                {");
            foreach (var p in ports)
            {
                sb.AppendLine($"                    [\"{p.FieldName}\"] = {PortIdLiteral(p.PortId)},");
            }

            sb.AppendLine("                },");
        }
    }
}
