using UnityEngine;
using Scaffold.AutoPacker;

namespace Scaffold.Autopacker.Samples
{
    [AutoPack]
    public partial class PlayerData
    {
        [Packed] public int Health;
        [Packed] public float Speed;
        [Packed] public Vector3 Position;
        
        // This won't be packed
        public string TemporaryBuffs;
    }

    public class AutoPackerUseCase : MonoBehaviour
    {
        private void Start()
        {
            // 1. Create our object
            var player = new PlayerData() { Health = 100, Speed = 5.5f, Position = new Vector3(10, 0, 5) };

            Debug.Log($"Original Player: Health={player.Health}, Speed={player.Speed}, Position={player.Position}");

            // 2. Pack the data to a struct (zero-allocation serialization)
            // .Pack() is generated by the AutoPacker Generator from the attributes above.
            IPackedStruct packedData = player.Pack();

            // 3. You could send this struct over the network, save it, etc...

            // 4. Reconstruct the object from the packed struct via constructor
            // A new constructor taking the generated Packed struct is auto-created.
            var restoredPlayer = new PlayerData((PlayerData.Packed)packedData);

            Debug.Log($"Restored Player: Health={restoredPlayer.Health}, Speed={restoredPlayer.Speed}, Position={restoredPlayer.Position}");
        }
    }
}
